openapi: 3.0.0
info:
  title: Training Management API
  description: API for managing training programs in the teaching system.
  version: 1.0.0
paths:
  /v1/Training-Management:
    get:
      summary: Retrieve a paginated list of training programs.
      operationId: listTraining
      responses:
        '200':
          description: A paginated list of training programs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Training'
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total:
                        type: integer
                      per_page:
                        type: integer
                      last_page:
                        type: integer
                required:
                  - data
                  - meta
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
    post:
      summary: Store a new training program.
      operationId: storeTraining
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '201':
          description: The newly created training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
  /v1/Training-Management/{trainingId}:
    get:
      summary: Retrieve a specific training program by its ID.
      operationId: showTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update an existing training program.
      operationId: updateTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '200':
          description: The updated training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete a specific training program.
      operationId: deleteTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Training program deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Training:
      type: object
      properties:
        id:
          type: string
        training_name:
          type: string
        training_description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - training_name
        - created_at
        - updated_at
