openapi: 3.0.0
info:
  title: Teaching Management API
  description: API for managing subjects, periods, and training programs in the teaching system.
  version: 1.0.0
paths:
  /v1/Teaching-unit/Subject/Course:
    get:
      summary: Retrieve a paginated list of all subjects.
      operationId: listSubjects
      responses:
        '200':
          description: A paginated list of subjects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
    post:
      summary: Store a new subject.
      operationId: storeSubject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '201':
          description: The newly created subject.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
  /v1/Teaching-unit/Subject/Course/{subjectId}:
    get:
      summary: Retrieve a specific subject by its ID.
      operationId: showSubject
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested subject.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
        '404':
          description: Subject not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update an existing subject.
      operationId: updateSubject
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '200':
          description: The updated subject.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
        '404':
          description: Subject not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete a specific subject.
      operationId: deleteSubject
      parameters:
        - name: subjectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Subject deleted successfully.
        '404':
          description: Subject not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /v1/Teaching-unit/Periods-Management:
    get:
      summary: Retrieve a paginated list of periods.
      operationId: listPeriods
      responses:
        '200':
          description: A paginated list of periods.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Period'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
    post:
      summary: Store a new period.
      operationId: storePeriod
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Period'
      responses:
        '201':
          description: The newly created period.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Period'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
  /v1/Teaching-unit/Periods-Management/Show/{periodId}:
    get:
      summary: Retrieve a specific period by its ID.
      operationId: showPeriod
      parameters:
        - name: periodId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested period.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Period'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
        '404':
          description: Period not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update an existing period.
      operationId: updatePeriod
      parameters:
        - name: periodId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Period'
      responses:
        '200':
          description: The updated period.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Period'
        '404':
          description: Period not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete a specific period.
      operationId: deletePeriod
      parameters:
        - name: periodId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Period deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Period'
        '404':
          description: Period not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /v1/Training-Management:
    get:
      summary: Retrieve a paginated list of training programs.
      operationId: listTraining
      responses:
        '200':
          description: A paginated list of training programs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Training'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
    post:
      summary: Store a new training program.
      operationId: storeTraining
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '201':
          description: The newly created training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
  /v1/Training-Management/{trainingId}:
    get:
      summary: Retrieve a specific training program by its ID.
      operationId: showTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          headers:
            X-Action-Title:
              description: The action performed.
              schema:
                type: string
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update an existing training program.
      operationId: updateTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '200':
          description: The updated training program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete a specific training program.
      operationId: deleteTraining
      parameters:
        - name: trainingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Training program deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Training program not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Subject:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Period:
      type: object
      properties:
        id:
          type: string
        period_name:
          type: string
        period_description:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Training:
      type: object
      properties:
        id:
          type: string
        training_name:
          type: string
        training_description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
